version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Contraseña para el usuario root
      MYSQL_DATABASE: ${DB_DATABASE}       # Nombre de la base de datos que deseas crear
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
